"""Add first_name and last_name to User model

Revision ID: 043576eaf03e
Revises: c3dbb8e30cac
Create Date: 2025-05-08 16:06:36.348443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043576eaf03e'
down_revision = 'c3dbb8e30cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
